name: rescue_mesh
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.3.0
  path_provider: ^2.1.2
  uuid: ^4.2.1

  nearby_connections: ^3.3.0

  geolocator: ^10.1.0
  permission_handler: ^11.3.0

  record: ^6.1.2

  battery_plus: ^5.0.2
  connectivity_plus: ^5.0.2
  http: ^1.1.0

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
